### ISSUE TITLE
Wrong energy measuring with SP 120

### ISSUE THREAD

**Issue by RicM27** [kasteleman/com.innr#13]
Using this app to control a couple of SP 120 wall plug with the Homey.

The current power display seems to be okay.

The recorded total energy usage only shows about 10% of the actual usage, with all of the wall plugs.

Seems there is a factor 10 miscalculation somewhere....

Best regards,

Richard,
![naamloos](https://user-images.githubusercontent.com/46974662/51631150-3c3b3700-1f4c-11e9-97b3-392fefaa4b04.png)

**Comment by neluzwr** [comment]
I've got the same issue. But also the recorded energy keeps resetting itself multiple times?

![image](https://user-images.githubusercontent.com/48013610/53404580-41116180-39b6-11e9-9ce8-252ceb22670b.png)

**Comment by kasteleman** [comment]
I asume you are on firmware 2.x.x

Can not reproduce at this moment. Don’t have firmware 2.x.x installed. Have
to migrate some apps before I can. But will have a look as soon as possible.

Regards,

Martin

Op di 26 feb. 2019 om 11:04 schreef neluzwr <notifications@github.com>

**Comment by neluzwr** [comment]
Hi Martin, that's correct I'm on 2.0.4 . Tnx!

**Comment by Martin1985as** [comment]
Does anyone has an update on this? Is this already solved?

**Comment by neluzwr** [comment]
No my issue still exists unfortunately.

**Comment by neluzwr** [comment]
I noticed the energy measuring is correct now! Thanks @kasteleman I saw you did an update 11 days ago.

**Comment by kasteleman** [comment]
That's correct. Sorry for not reporting that in this issue. Had a similar issue with the plugwise Zigbee app and applied the changes also to the INNR app. Thx for the feedback!
