### ISSUE TITLE
Support for G10 RS 128 T

### ISSUE THREAD

**Issue by vogon1** [kasteleman/com.innr#2]
Hi,

I bought this: https://www.robbshop.nl/gu10-tunable-spot-fourpack-zigbee-innr

I can get those lights to work with this patch:

diff --git a/app.json b/app.json
index 784a3b1..f84070a 100644
--- a/app.json
+++ b/app.json
@@ -184,8 +184,8 @@
       ],
       "zigbee": {
         "manufacturerName": "innr",
-        "productId": [ "RS 125", "RS 122" ],
-        "deviceId": 256,
+        "productId": [ "RS 125", "RS 122" , "RS 128 T" ],
+        "deviceId": [ 256, 544],
         "profileId": 49246,
         "learnmode": {
           "image": "/drivers/dimmable_gu10/assets/icon.svg",

Sietse

**Comment by kasteleman** [comment]
That will get them going, but you are unable to change it to warm or cooler.
I hope to receive a bulb this week so I can test them and add them to the app.
But good you put in the details, so that could get me started.
I let you know as soon I have added them.

Regards,

Martin

**Comment by kasteleman** [comment]
Sietse,

can you please test the new commit in the master branch by installing it from the cli?
As noted before: keep in mind you have to exclude and include the GU10!

**Comment by vogon1** [comment]
Hi,

I can confirm this driver can set the temperature of the light, the color is between white and yellow.

Thanks!

**Comment by kasteleman** [comment]
Top, thx for the feedback
