### ISSUE TITLE
Pucks added as unknown device

### ISSUE THREAD

**Issue by moekdegroot** [kasteleman/com.innr#3]
Hi @kasteleman ,

First, thanks for creating this app!
I just ran in to a problem adding the innr pucks.
They're added as an unknown device.
I've reset them a couple of times and PtP'ed Homey but the result stays the same.

Moek
![schermafbeelding 2017-11-18 om 11 45 00](https://user-images.githubusercontent.com/16590284/32979503-a36f618e-cc56-11e7-82dd-5d1c37be8626.png)

**Comment by kasteleman** [comment]
THX for reporting.
Was a type in the app.json
Fixed it. Can you test with side loading the app?

**Comment by moekdegroot** [comment]
Going to sideload now.
Thanks!

**Comment by moekdegroot** [comment]
Yes, it worked!
They're added as pucks.
However, the brightness bug I have with the strips is also present with the pucks...
Do you know if there is a way of upgrading the firmware without a bridge?
I'm afraid I already know the answer but you never know ;)
Anyway, thanks for the quick response!

**Comment by kasteleman** [comment]
I have to check with INNR.

I’ll let you know.

Regards,

Martin

Op za 18 nov. 2017 om 12:58 schreef moekdegroot <notifications@github.com>

**Comment by kasteleman** [comment]
I can confirm it is a firmware bug for both devices.
There may be a workaround by rewriting the on off part for the devices. Will have a look. Only thing is, I don't own those devices, so can't test the code myself.

**Comment by moekdegroot** [comment]
He Martin,
I will be more then happy to test. 
Just say the word and I’ll sideload it. 
Thanks again!
