### ISSUE TITLE
INNR 

### ISSUE THREAD

**Issue by Paulus987** [kasteleman/com.innr#9]
Hello,

I have bought a INNR lamp, and want to add it to my Homey (supplied with the INNR App). But the lamp doesn't get recognized as a lamp by Homey. It's just been added as a general zigbee device. Can you add this lamp to the firmware/app of INNR? It's the newer type of the RB185-C, type RB285C. 

 INN_E27 RB285C  RGWB lamp

Thanks

**Comment by kasteleman** [comment]
I’m already on to it.
Received the RB 285 C Yesterday.
Thx INNR!

It is functional already, but have to fine tune the driver because this
bulb has sweet zigbee 3.0 support. Therefore attribute reporting is
supported mandatory and I want to implement that. Did you already noticed
that the bulb remembers the last selected color and brightness even after a
power cut?

Regards,

Martin

Op wo 10 okt. 2018 om 10:48 schreef Paulus987 <notifications@github.com>

**Comment by Paulus987** [comment]
Hello Martin,

Thanks for the quick reply. No i didn't notice that because now it only shines white and i cannot do anything with it through homey or the homey app. Not dimmable and not adjusting colour.

**Comment by Paulus987** [comment]
And the INNR app requires the INNR bridge for setup, but i only have the Homey.

**Comment by kasteleman** [comment]
No no, i’m Updating the innr app for Homey for the bulb. So then you
install that app on Homey and then include the bulb. No bridge required!
So be a little patient with me 😉 it will be supported

Op wo 10 okt. 2018 om 11:46 schreef Paulus987 <notifications@github.com>

**Comment by Paulus987** [comment]
Ok thanks! I will wait on your update. thanks a lot!

**Comment by kasteleman** [comment]
I updated the master branch with initial support for the RB 285 C and BY 285 C. Can you test it by side loading it from the cli?

**Comment by Paulus987** [comment]
Thanks, but don’t know what you mean or what to do? I’ve just bought a homey and the lamp a few days ago and not so familiair with the terms and settings ;)?

**Comment by kasteleman** [comment]
Ok, didn’t know that. You can search the forum for how to sideload or you
have to wait until Athom approves my updated app and i can push it to
Athoms app store.

Op za 13 okt. 2018 om 09:36 schreef Paulus987 <notifications@github.com>

**Comment by Paulus987** [comment]
Ooh okey thanks, then i’ll wait. Still busy with the fibaro switches and dimmers haha

**Comment by kasteleman** [comment]
Update is available in the Athom's App Store now

**Comment by Paulus987** [comment]
Thanks! Its working now!

Met vriendelijke groet,

Paul Verhoeven


————————————————
Verstuurd vanaf mijn iPhone

Op 18 okt. 2018 om 18:49 heeft kasteleman <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Update is available in the Athom's App Store now
